In [1]:
import sys
import os
sys.path.insert(0, os.path.join(os.getcwd(), '../core'))
import kaggle_support as kgs
import importlib
import matplotlib.pyplot as plt
import numpy as np
import cupy as cp
from dataclasses import dataclass, field, fields
import pack_cuda
import pack_vis
import pack_cost
import copy
import time
import pack_ga
from IPython.display import HTML, display, clear_output
pack_cuda.USE_FLOAT32 = False
pack_cuda._ensure_initialized()


local
local
stop final relax at some point


In [ ]:
importlib.reload(pack_ga)
fastMode = False
runner = pack_ga.GA()

# fast for now
#runner.population_size = 1
#runner.selection_size = [0]
#runner.n_generations = 500

# structural
runner.N_trees_to_do = np.array([8])
runner.population_size = 10000
runner.n_generations = 30
runner.plot_fitness_predictors = False
runner.plot_diversity_matrix = False
runner.plot_champions = False
runner.initializer.base_solution = kgs.SolutionCollectionLattice()
runner.initializer.jiggler.duration_init = 0.
runner.initializer.jiggler.duration_compact /= 100000
runner.initializer.jiggler.duration_final = 0.
runner.initializer.jiggler.plot_interval = None
runner.initializer.jiggler.n_rounds = 1
runner.rough_relaxers[0].plot_interval =None
runner.rough_relaxers[0].n_iterations//=5
runner.fine_relaxers[0].plot_interval=None
runner.rough_relaxers[0].cost.costs.pop(1)
runner.fine_relaxers[0].cost.costs.pop(1)
runner.fine_relaxers[0].n_iterations//=5
runner.fitness_cost.costs.pop(1)
kgs.debugging_mode = 1
kgs.profiling=False
new_moves = []
for i in [1,2,3,4,5]:
    new_moves.append(runner.move.moves[i])
runner.move.moves = new_moves
#runner.rough_relaxers = []
#runner.fine_relaxers = []
for seed in range(1000):
    run = copy.deepcopy(runner)
    run.seed = seed
    run.run()
    kgs.dill_save(kgs.temp_dir+'res'+str(seed)+'.pickle', run)

stop final relax at some point
Generation 0, Trees 3, Best cost: 0.01022896, Est: 0.34096531, h: 1.024546
[[1.0245456 0.9944389 1.5007831]]
Generation 1, Trees 3, Best cost: 0.01022888, Est: 0.34096265, h: 1.024373
[[1.0243734 0.9945691 1.5009682]]
Generation 2, Trees 3, Best cost: 0.01022879, Est: 0.34095959, h: 1.025024
[[1.0250239 0.9942861 1.5002464]]
Generation 0, Trees 3, Best cost: 0.01024030, Est: 0.34134324, h: 1.063552
[[1.0635524 0.9605529 1.6358857]]
Generation 1, Trees 3, Best cost: 0.01022881, Est: 0.34096038, h: 1.024541
[[1.0245415 0.9944839 1.6407785]]
Generation 2, Trees 3, Best cost: 0.01022869, Est: 0.34095625, h: 1.025298
[[1.025298  0.9940173 1.5004051]]


In [ ]:
runner.rough_relaxers[0].cost

CostCompound(comment='', scaling=1.0, costs=[AreaCost(comment='', scaling=0.01), CollisionCostOverlappingArea(comment='', scaling=1.0)])